package com.purestorage.dev.pureintent.messaging;

public enum MessageType {
	NEED_HELP_MESSAGE, UPDATE_HELP_MESSAGE, 
	UPDATE_SETTINGS_MESSAGE, GET_HELPER_MESSAGE, 
	UPDATE_HELPER_MESSAGE, REGISTRATION_MESSAGE,
	ON_MY_WAY_MESSAGE, HELP_INCOMING_MESSAGE, 
	HELP_RECEIVED_MESSAGE, REQUEST_CLOSED_MESSAGE
}
